format = """
â² $directoryâ³\
$character"""

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = "[ ïŸ˜](bold bright-orange)"
error_symbol = "[ ïŸ˜](bold dark-red)"

[line_break]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[directory]
style = "bold bright-red"
truncation_length = 8
truncation_symbol = "â€¦/"
read_only = "ğŸ”’"
use_os_path_sep = true

[python]
disabled = true

